# Generated by Django 2.2.11 on 2020-03-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_group_groupmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(to="users.Group"),
        ),
        migrations.DeleteModel(name="GroupMembership",),
    ]
