# This is a basic workflow to help you get started with Actions

name: Server Code Checks

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x' 
        architecture: 'x64' 

    - name: Run a multi-line script
      run: |
        python -m pip install --upgrade pip
        cd server
        pip install -r requirements.txt

        # lint
        flake8 .

        # code formatting
        black .
